version: "3.8"

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    restart: always

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - app

  celery:
    container_name: celery
    build: .
    command: celery -A src.celery.celery_worker.app worker -B --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A src.celery.celery_worker.app flower --port=5555 --persistent --db=/flower/data/flower.db
    ports:
      - "5555:5555"
    volumes:
      - flower-data:/flower/data
    depends_on:
      - app
      - redis
      - celery

volumes:
  flower-data:
    driver: local
