version: "3.8"

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    restart: always
    networks:
      - app-network

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - app
    networks:
      - app-network

  celery:
    container_name: celery
    build: .
    command: celery -A src.celery.celery_worker.app worker -B --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
    networks:
      - app-network

  flower:
    container_name: flower
    build: .
    command: celery -A src.celery.celery_worker.app flower --port=5555 --persistent --db=/flower/data/flower.db
    ports:
      - "5555:5555"
    volumes:
      - flower-data:/flower/data
    depends_on:
      - app
      - redis
      - celery
    networks:
      - app-network

  streamlit:
    container_name: streamlit-app
    build:
      context: ./streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  flower-data:
    driver: local

networks:
  app-network:
    driver: bridge